### ISSUE TITLE
Suggestion: Use Google Analytics

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/libresprite.github.io#10]
We can use Google Analytics to keep a statistical record of how many people visit the website or download the software in order to measure the interest of users. What do you think?

**Comment by Calinou** [comment]
I would prefer not, as Google Analytics is known for its less-than-ideal privacy practices.

**Comment by maujin111** [comment]
@Calinou  Oh ok, I will check GitHub API to know how to display the number of downloads on the website, if that's ok

**Comment by MintStudios** [comment]
@maujin111 I'm pretty sure there is a badge in shields.io for github downloads.

**Comment by maujin111** [comment]
@MintStudios I'ḿ checking that right know, later today i'll make a pull request to update the website front-end a little bit,

**Comment by PerryHugh** [comment]
With the badge added (much better alternative imo), is it necessary to keep this issue open?
