### ISSUE TITLE
Use a Standard font and color palette

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/libresprite.github.io#11]
Given the need to rebrand LibreSprite and separate it from its brother's shadow. I would like to hear your proposals. Starting with a standard font and color pallete for everything related to libreprite such as the website, any graphic design, image for publication or even merchandise.

**Comment by PerryHugh** [comment]
Though a fallback is a good idea, I do like your original idea of a pixel font (preferably one matching the editor itself) to create a cohesive sense to the whole project.

I don't have the greatest eye for color.

**Comment by maujin111** [comment]
It's already implemented
