### ISSUE TITLE
Framework or librery for front-end

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/libresprite.github.io#14]
We should use some library or framework as angular or react?. 

I propose to use angular to make the page more dynamic and engaging

**Comment by Calinou** [comment]
I don't think we need to use a JavaScript framework on a static website. There are no practical upsides to it.

If you want pages to be prefetched on hover to speed up navigation, look into setting up [instant.page](https://instant.page) instead. (Or, better, [Barba.js](https://barba.js.org/) but keep in mind it requires more setup.)

**Comment by PerryHugh** [comment]
I agree. JavaScript should not be necessary for what needs to be displayed on the site. That being said, if you come across some neat pixel art that could be displayed with a parallax background or in some way improved by rudimentary JavaScript, I would be all for it.
