### ISSUE TITLE
Is this piracy?

### ISSUE THREAD

**Issue by Sosasees** [LibreSprite/libresprite.github.io#16]
I wonder if LibreSprite is actually pirated Asperite.
LibreSprite sounds awesome on paper, but I really don't want to pirate software

**Comment by Calinou** [comment]
LibreSprite is based on the last GPLv2-licensed commit of Aseprite. It's perfectly legal, as the license allows redistribution of (un)modified works as long as it's distributed under the same license.

**Comment by Sosasees** [comment]
Oh wait, are Authors actually allowed to change GPL-licensed software to have another incompatible license?

**Comment by Calinou** [comment]
> Oh wait, are software authors actually allowed to change their GPL-licensed software to have another, GPL-incompatible license?

Yes, as long as the author holds its copyright or is given permission to change the code's license. This is the case in Aseprite, as the main author asks people to sign a contributor license agreement when they open pull requests.

**Comment by Sosasees** [comment]
Thanks very much! Now I'm in the clear that LibreSprite is legal software and definitely NOT piracy, because it's based only off GPL-licensed parts of the Aseprite code.

**Comment by MintStudios** [comment]
I would definitely not want LibreSprite to be seen as privacy, but more like a FOSS alternative. (Even though Aseprite code is on github )
