### ISSUE TITLE
WordPress access

### ISSUE THREAD

**Issue by MintStudios** [LibreSprite/libresprite.github.io#17]
I haven't heard about the website too much, but I think that it's made from WordPress. This is fine for now, but how can I access the website. I'm looking to make some changes to the site. Also, should site changes be reviewed?

**Comment by Calinou** [comment]
GitHub Pages doesn't run WordPress. It's a static site hosting solution which can optionally integrate with [Jekyll](https://jekyllrb.com).

**Comment by MintStudios** [comment]
@Calinou I opened this issue in the website repo, but http://www.libresprite.org/ is running on WordPress, and not on github pages.

**Comment by MintStudios** [comment]
Perry Hugh has sent me admin details.
