### ISSUE TITLE
Delete Repo

### ISSUE THREAD

**Issue by PerryHugh** [LibreSprite/libresprite.github.io#18]
I'm considering deleting this repository, but want to give anyone who wants to download it a chance to do so or argue a reason to keep it.

Thoughts?

**Comment by Calinou** [comment]
Out of curiosity, why does this repository need to be deleted? What's the official website now?

**Comment by MintStudios** [comment]
@Calinou the website is at http://libresprite.org

**Comment by SimoneStarace** [comment]
> @Calinou the website is at http://libresprite.org

I tried to connect to the website but it seems it doesn't exist.

> And yes, I think we should delete this repo because it is unnecessary and may cause confusion.

I don't know why you would erase this repository. I have seen some people making specific repositories for their open source projects.

**Comment by maujin111** [comment]
For now, this is the only website to download Libresprite for the end user.
