### ISSUE TITLE
There is too much spam on the forum

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/libresprite.github.io#19]
There is too much spam on the forum, we have to do something. I already manage to ban some users and delete some posts but, ne ones are created every day. @MintStudios

**Comment by MintStudios** [comment]
Hmmm. I'm not sure what to do. I have never maintained a forum before, so I don't know what antispam measures we could use.

**Comment by maujin111** [comment]
I suppose we need an administrator for the forum who has experience, I really started a new job with a new project and I only have a short time to review what happens there and delete one or another spam,
@MintStudios Do you think it is a good idea to ask for volunteers on the Discord channel?

**Comment by MintStudios** [comment]
Maybe, I'm not sure what the level of trust would be. I think we should open an issue and take anyone that might have some experience.

**Comment by jpellegrini** [comment]
Hello!
If I understand correctly, you are using phpBB for the forum. I would suggest this:
- require registration with Q&A (some question that cannot be googled/trivially answered)
- put each new user's _first_ post in a approval queue
That would probably help a lot...

**Comment by maujin111** [comment]
Forum is close
