### ISSUE TITLE
 Stop using the wiki and use Sphinx for documentation

### ISSUE THREAD

**Issue by maujin111** [LibreSprite/libresprite.github.io#21]
Personally, I do not consider a wiki necessary for this kind of project, it is necessary to use a dedicated tool for generating documentation. An excellent alternative is [Sphinx](https://www.sphinx-doc.org/en/master/). It is easy to use and implement, it is also used by many free software projects (as Godot) to manage their documentation.

**Comment by Calinou** [comment]
> it is necessary to use a dedicated tool for generating documentation. 

Can you explain why it's necessary? I consider a GitHub wiki to be perfectly fine for small-scale projects.

**Comment by maujin111** [comment]
sorry, what I was referring to is the use of the wiki that is currently on the main page, [this one](http://libresprite.org/wiki/index.php/Main_Page). It is full of articles that have nothing to do with the project, bots and spam. Using the github wiki also seems like a good alternative

**Comment by maujin111** [comment]
The LibreSprite GitHub wiki is implemented
