### ISSUE TITLE
Redesign the site to look more like pixelart?

### ISSUE THREAD

**Issue by sukhchainn** [LibreSprite/libresprite.github.io#26]
I downloaded the libresrite executable from the site and was very impressed on how much this looks like asprite and it can even open the latest asprite files too. I was wondering why you guys didn't implement a pixelart style for the website and if I can do something for the design, I would like to help in that regard.

**Comment by maujin111** [comment]
> I downloaded the libresrite executable from the site and was very impressed on how much this looks like asprite and it can even open the latest asprite files too. I was wondering why you guys didn't implement a pixelart style for the website and if I can do something for the design, I would like to help in that regard.

That would be great! If you have any idea, please share it

**Comment by sukhchainn** [comment]
I have forked this repo, I'm going to make some changes and when I'm done let's see what changes are acceptable and what we can do to improve it.

**Comment by sukhchainn** [comment]
For now I have just changed the bootstrap icons with pixelart version of them. If you like any changes then do let me know.
