### ISSUE TITLE
Wiki shows unavailable feature

### ISSUE THREAD

**Issue by jgibbons94** [LibreSprite/libresprite.github.io#45]
At the very bottom of the [Know Your Workspace Wiki page](https://github.com/LibreSprite/libresprite.github.io/wiki/Know-your-workspace), it says the following:

> <p>If you want to export with a different size, the "save copy as" item in the file menu has a "resize" option.</p> <p><img src="https://camo.githubusercontent.com/229a8612f5b83ae22cb9fbc3581a793c58a45035aa65178dce2098a53e7faf74/68747470733a2f2f696d61676573322e696d67626f782e636f6d2f31342f38322f6c61616f765971725f6f2e706e67" alt="" data-canonical-src="https://images2.imgbox.com/14/82/laaovYqr_o.png"></p>

I have built libresprite from the master branch (8fa1f8959e02464fb3edbb9d6804fed977b09a21 as of time of writing, using guix package manager), and there is no such field on the save dialog. The field isn't even shown on the screenshot just above that quote showing the save dialog layout.
> <p><img src="https://camo.githubusercontent.com/6b199496b18c6b327fe966ee3306ce7f19f83c7add11fd9aa10f785537679c5f/68747470733a2f2f696d61676573322e696d67626f782e636f6d2f34612f63302f75544a715a4c70705f6f2e706e67" alt="" data-canonical-src="https://images2.imgbox.com/4a/c0/uTJqZLpp_o.png"></p>

Is this a feature that has yet to be merged?

**Comment by jgibbons94** [comment]
Here's what I see. ![image](https://user-images.githubusercontent.com/21369633/148301542-8d2684d3-677b-4f0e-98fe-8e3a6d58cf90.png)

**Comment by maujin111** [comment]
the option is on: "save copy as" not "save copy"
